import { CreditCard, CheckCircle, AlertCircle } from 'lucide-react'
import { Card, CardHeader, CardContent } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { FinanceDownloadButton } from '@/components/finance/FinanceDownloadButton'
import { getFinanceData } from '@/services/finance-queries'
import { formatRM, formatDate } from '@/lib/utils'
import type { Invoice, Payment, InvoiceStatus } from '@/types/financial'

import { auth } from '@/auth'
import { redirect } from 'next/navigation'

const STATUS_VARIANT: Record<InvoiceStatus, 'success' | 'warning' | 'danger' | 'neutral'> = {
  paid:      'success',
  partial:   'warning',
  unpaid:    'danger',
  overdue:   'danger',
  cancelled: 'neutral',
}

const PAYMENT_STATUS_VARIANT: Record<Payment['status'], 'success' | 'warning' | 'danger' | 'neutral'> = {
  completed: 'success',
  pending: 'warning',
  failed: 'danger',
  refunded: 'neutral',
}

function invoiceText(inv: Invoice): string {
  return [
    'UCSI College — Fee Statement',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `Invoice No. : ${inv.invoiceNumber}`,
    `Semester    : ${inv.programmeSemester}`,
    `Issued      : ${inv.issuedAt}`,
    `Due Date    : ${inv.dueDate}`,
    '',
    `Tuition Fee : RM ${inv.tuitionFee.toFixed(2)}`,
    `Outstanding : RM ${inv.amountOutstanding.toFixed(2)}`,
    `Status      : ${inv.status.toUpperCase()}`,
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'This is a demo document generated by the UCSI Student Portal.',
    'For official records, contact the Finance Office.',
  ].join('\n')
}

function paymentReceiptText(pmt: Payment): string {
  return [
    'UCSI College — Payment Receipt',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `Transaction : ${pmt.transactionNumber}`,
    `Reference   : ${pmt.referenceNo ?? '—'}`,
    `Date        : ${pmt.paymentDate}`,
    `Method      : ${pmt.mode.toUpperCase()}`,
    `Amount      : RM ${pmt.amount.toFixed(2)}`,
    `Status      : ${pmt.status.toUpperCase()}`,
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'This is a demo document generated by the UCSI Student Portal.',
    'For official records, contact the Finance Office.',
  ].join('\n')
}

export default async function FinancePage() {
  const session = await auth()
  const studentId = session?.user?.studentId
  if (!studentId) redirect('/login')
  const { invoices, payments } = await getFinanceData(studentId)

  const totalOutstanding = invoices.reduce((s, i) => s + i.amountOutstanding, 0)
  const totalPaid = payments.reduce(
    (sum, payment) => sum + (payment.status === 'completed' ? payment.amount : 0),
    0,
  )

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-xl font-semibold text-[--text-primary]">Financial</h1>
        <p className="mt-0.5 text-sm text-[--text-secondary]">Fee statements and payment history</p>
      </div>

      {/* Summary */}
      <div className="grid gap-3 sm:grid-cols-3">
        <Card>
          <CardContent>
            <div className="flex items-center gap-3">
              <AlertCircle size={18} className="text-[--ucsi-red]" aria-hidden="true" />
              <div>
                <p className="text-xs text-[--text-secondary]">Outstanding Balance</p>
                <p className="text-xl font-bold text-[--text-primary]">{formatRM(totalOutstanding)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent>
            <div className="flex items-center gap-3">
              <CheckCircle size={18} className="text-emerald-500" aria-hidden="true" />
              <div>
                <p className="text-xs text-[--text-secondary]">Total Paid</p>
                <p className="text-xl font-bold text-[--text-primary]">{formatRM(totalPaid)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent>
            <div className="flex items-center gap-3">
              <CreditCard size={18} className="text-[--text-secondary]" aria-hidden="true" />
              <div>
                <p className="text-xs text-[--text-secondary]">Total Invoiced</p>
                <p className="text-xl font-bold text-[--text-primary]">
                  {formatRM(invoices.reduce((s, i) => s + i.tuitionFee, 0))}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Invoice table */}
      <Card>
        <CardHeader>
          <h2 className="text-sm font-semibold text-[--text-primary]">Fee Statements</h2>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[580px] text-left" aria-label="Fee statements">
              <thead>
                <tr className="border-b border-[--ucsi-border]">
                  {['Invoice No.', 'Semester', 'Due Date', 'Amount (RM)', 'Outstanding', 'Status', ''].map((h) => (
                    <th key={h} scope="col" className="pb-2 pr-4 text-[10px] font-semibold uppercase tracking-wide text-[--text-secondary]">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {invoices.map((inv) => (
                  <tr key={inv.id} className="border-b border-[--ucsi-border] last:border-0 hover:bg-zinc-50 dark:hover:bg-white/5">
                    <td className="py-3 pr-4 font-mono text-xs text-[--text-secondary]">{inv.invoiceNumber}</td>
                    <td className="py-3 pr-4 text-sm text-[--text-primary]">{inv.programmeSemester}</td>
                    <td className="py-3 pr-4 text-xs text-[--text-secondary]">{formatDate(inv.dueDate)}</td>
                    <td className="py-3 pr-4 text-sm font-medium text-[--text-primary]">{formatRM(inv.tuitionFee)}</td>
                    <td className="py-3 pr-4 text-sm">
                      <span className={inv.amountOutstanding > 0 ? 'font-semibold text-[--ucsi-red]' : 'text-[--text-muted]'}>
                        {inv.amountOutstanding > 0 ? formatRM(inv.amountOutstanding) : '—'}
                      </span>
                    </td>
                    <td className="py-3 pr-4">
                      <Badge variant={STATUS_VARIANT[inv.status]}>
                        {inv.status.charAt(0).toUpperCase() + inv.status.slice(1)}
                      </Badge>
                    </td>
                    <td className="py-3">
                      <FinanceDownloadButton
                        filename={`${inv.invoiceNumber}.txt`}
                        content={invoiceText(inv)}
                        label={`Download invoice ${inv.invoiceNumber}`}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Payment history */}
      <Card>
        <CardHeader>
          <h2 className="text-sm font-semibold text-[--text-primary]">Payment History</h2>
        </CardHeader>
        <CardContent>
          {payments.length === 0 ? (
            <p className="py-4 text-center text-sm text-[--text-muted]">No payments recorded.</p>
          ) : (
            <div className="flex flex-col divide-y divide-[--ucsi-border]">
              {payments.map((pmt) => (
                <div key={pmt.id} className="flex items-center justify-between py-3">
                  <div>
                    <p className="text-sm font-medium text-[--text-primary]">{formatRM(pmt.amount)}</p>
                    <p className="text-xs text-[--text-secondary]">
                      {[pmt.mode.toUpperCase(), pmt.referenceNo, formatDate(pmt.paymentDate)]
                        .filter(Boolean)
                        .join(' · ')}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant={PAYMENT_STATUS_VARIANT[pmt.status]}>
                      {pmt.status.charAt(0).toUpperCase() + pmt.status.slice(1)}
                    </Badge>
                    <FinanceDownloadButton
                      filename={`receipt-${pmt.transactionNumber}.txt`}
                      content={paymentReceiptText(pmt)}
                      label={`Download receipt for ${pmt.transactionNumber}`}
                    />
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
